---
  - hosts: docker
    remote_user: augusto
    become: yes
    tasks:
      - name: "Executa o container MySQL"
        docker_container:
          name: banco
          image: mysql:5.6
          env:
            MYSQL_ROOT_PASSWORD: senha123
      - name: "Executa o container WordPress"
        docker_container:
          name: wordpress2
          image: wordpress
          links:
            - "banco:mysql"
          ports:
            - "8080:80"
